# Generated by Django 3.2 on 2022-09-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dueño',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('edad', models.BigIntegerField()),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Gato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('raza', models.CharField(max_length=60)),
                ('sexo', models.CharField(max_length=60)),
                ('edad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Perro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('raza', models.CharField(max_length=60)),
                ('sexo', models.CharField(max_length=60)),
                ('edad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Roedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('raza', models.CharField(max_length=60)),
                ('sexo', models.CharField(max_length=60)),
                ('edad', models.IntegerField()),
            ],
        ),
    ]
