# Generated by Django 3.2 on 2022-09-29 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppLuna', '0002_auto_20220929_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dueno',
            name='correo',
        ),
    ]
